"""Safe, switchable request-processing backends for Python crawlers."""

from . import signals
from .addons import AddonManager
from .api import (
    DupeFilter,
    Scheduler,
    fingerprint,
    fingerprint_batch,
    fingerprint_request,
    fingerprint_requests,
)
from .backend import (
    BACKEND_ENV_VAR,
    BackendChoice,
    BackendUnavailableError,
    resolve_backend,
)
from .cookies import CookiesMiddleware
from .crawl import CrawlSpider, Rule
from .crawler import (
    AsyncCrawlerProcess,
    AsyncCrawlerRunner,
    Crawler,
    CrawlerProcess,
    CrawlerRunner,
)
from .depth import DepthMiddleware
from .downloader import Downloader, HttpxDownloader, RustDownloader
from .downloadermiddlewares import (
    DefaultHeadersMiddleware,
    DownloaderStatsMiddleware,
    DownloadTimeoutMiddleware,
    HttpAuthMiddleware,
    HttpCompressionMiddleware,
    OffsiteMiddleware,
    UserAgentMiddleware,
)
from .downloadhandlers import (
    BaseDownloadHandler,
    DataURIDownloadHandler,
    DownloadHandler,
    DownloadHandlers,
    FileDownloadHandler,
    FTPDownloadHandler,
    HTTPDownloadHandler,
    S3DownloadHandler,
)
from .engine import CrawlResult, NativeCrawlEngine
from .exceptions import (
    CloseSpider,
    DontCloseSpider,
    DownloadError,
    DropItem,
    IgnoreRequest,
    NotConfigured,
    NotSupported,
    SpiderOxideError,
    StopDownload,
)
from .extensions import ExtensionManager
from .feedexport import (
    BaseItemExporter,
    BlockingFeedStorage,
    CsvItemExporter,
    FeedExporter,
    FeedSlot,
    FileFeedStorage,
    FTPFeedStorage,
    GCSFeedStorage,
    ItemFilter,
    JsonItemExporter,
    JsonLinesItemExporter,
    MarshalItemExporter,
    PickleItemExporter,
    PprintItemExporter,
    PythonItemExporter,
    S3FeedStorage,
    StdoutFeedStorage,
    XmlItemExporter,
    apply_uri_params,
)
from .feedpostprocessing import Bz2Plugin, GzipPlugin, LZMAPlugin, PostProcessingManager
from .feedspiders import CSVFeedSpider, XMLFeedSpider
from .headers import Headers
from .http import (
    FormRequest,
    HtmlResponse,
    JsonRequest,
    Request,
    Response,
    TextResponse,
    XmlResponse,
)
from .httpcache import (
    DummyPolicy,
    HttpCacheMiddleware,
    NativeHttpCacheStorage,
    RFC2616Policy,
)
from .linkextractors import Link, LinkExtractor, LxmlLinkExtractor
from .operational import (
    CloseSpider as CloseSpiderExtension,
)
from .operational import (
    CoreStats,
    LogCount,
    LogStats,
    MemoryDebugger,
    MemoryUsage,
    PeriodicLog,
    SpiderState,
)
from .pipelines import (
    FileException,
    FileInfo,
    FilesPipeline,
    FSFilesStore,
    FTPFilesStore,
    GCSFilesStore,
    ImageException,
    ImagesPipeline,
    MediaPipeline,
    S3FilesStore,
)
from .proxy import HttpProxyMiddleware
from .redirect import MetaRefreshMiddleware, RedirectMiddleware
from .retry import RetryMiddleware, get_retry_request
from .selectors import (
    Compose,
    Identity,
    ItemLoader,
    Join,
    MapCompose,
    SelectJmes,
    Selector,
    SelectorList,
    TakeFirst,
)
from .services import ServiceManager
from .settings import BaseSettings, Settings, SettingsAttribute, get_settings_priority
from .signals import SignalManager
from .sitemap import Sitemap, SitemapSpider, sitemap_urls_from_robots
from .spider import Spider
from .spiderloader import SpiderLoader
from .spidermiddlewares import (
    BaseSpiderMiddleware,
    DefaultReferrerPolicy,
    HttpError,
    HttpErrorMiddleware,
    MetaCopyDetectionMiddleware,
    NoReferrerPolicy,
    NoReferrerWhenDowngradePolicy,
    OriginPolicy,
    OriginWhenCrossOriginPolicy,
    RefererMiddleware,
    ReferrerPolicy,
    SameOriginPolicy,
    StartSpiderMiddleware,
    StrictOriginPolicy,
    StrictOriginWhenCrossOriginPolicy,
    UnsafeUrlPolicy,
    UrlLengthMiddleware,
)
from .stats import StatsCollector
from .types import (
    Field,
    FingerprintRequest,
    Item,
    ItemAdapter,
    PriorityRequest,
    RequestData,
    ScheduledRequest,
)

__all__ = [
    "BACKEND_ENV_VAR",
    "AsyncCrawlerProcess",
    "AsyncCrawlerRunner",
    "AddonManager",
    "BackendChoice",
    "BackendUnavailableError",
    "BaseDownloadHandler",
    "BaseItemExporter",
    "BaseSettings",
    "BaseSpiderMiddleware",
    "BlockingFeedStorage",
    "Bz2Plugin",
    "CloseSpider",
    "CloseSpiderExtension",
    "Compose",
    "CoreStats",
    "CookiesMiddleware",
    "CSVFeedSpider",
    "Crawler",
    "CrawlerProcess",
    "CrawlerRunner",
    "CrawlSpider",
    "CrawlResult",
    "CsvItemExporter",
    "DownloadError",
    "DontCloseSpider",
    "DownloadHandler",
    "DownloadHandlers",
    "Downloader",
    "DownloaderStatsMiddleware",
    "DownloadTimeoutMiddleware",
    "DataURIDownloadHandler",
    "DefaultHeadersMiddleware",
    "DefaultReferrerPolicy",
    "DummyPolicy",
    "DepthMiddleware",
    "DropItem",
    "DupeFilter",
    "ExtensionManager",
    "Field",
    "FeedExporter",
    "FeedSlot",
    "FileException",
    "FingerprintRequest",
    "FileFeedStorage",
    "FileDownloadHandler",
    "FileInfo",
    "FilesPipeline",
    "FSFilesStore",
    "FTPFilesStore",
    "FormRequest",
    "FTPFeedStorage",
    "FTPDownloadHandler",
    "GCSFeedStorage",
    "GCSFilesStore",
    "GzipPlugin",
    "Headers",
    "HtmlResponse",
    "IgnoreRequest",
    "HttpAuthMiddleware",
    "HttpCompressionMiddleware",
    "HttpError",
    "HttpErrorMiddleware",
    "HttpxDownloader",
    "HTTPDownloadHandler",
    "HttpProxyMiddleware",
    "HttpCacheMiddleware",
    "ImageException",
    "ImagesPipeline",
    "Item",
    "ItemAdapter",
    "ItemFilter",
    "ItemLoader",
    "Identity",
    "JsonItemExporter",
    "JsonLinesItemExporter",
    "JsonRequest",
    "Join",
    "Link",
    "LinkExtractor",
    "LxmlLinkExtractor",
    "LZMAPlugin",
    "LogCount",
    "LogStats",
    "MarshalItemExporter",
    "MapCompose",
    "MediaPipeline",
    "MemoryDebugger",
    "MemoryUsage",
    "MetaCopyDetectionMiddleware",
    "MetaRefreshMiddleware",
    "SpiderState",
    "NotConfigured",
    "NotSupported",
    "NativeCrawlEngine",
    "NativeHttpCacheStorage",
    "NoReferrerPolicy",
    "NoReferrerWhenDowngradePolicy",
    "OffsiteMiddleware",
    "OriginPolicy",
    "OriginWhenCrossOriginPolicy",
    "PeriodicLog",
    "PickleItemExporter",
    "PostProcessingManager",
    "PprintItemExporter",
    "PriorityRequest",
    "PythonItemExporter",
    "Request",
    "RequestData",
    "RFC2616Policy",
    "RedirectMiddleware",
    "RefererMiddleware",
    "ReferrerPolicy",
    "Response",
    "RetryMiddleware",
    "Rule",
    "S3FeedStorage",
    "S3FilesStore",
    "S3DownloadHandler",
    "RustDownloader",
    "ScheduledRequest",
    "SameOriginPolicy",
    "SelectJmes",
    "Scheduler",
    "Selector",
    "SelectorList",
    "ServiceManager",
    "Settings",
    "SettingsAttribute",
    "SignalManager",
    "Sitemap",
    "SitemapSpider",
    "Spider",
    "SpiderLoader",
    "SpiderOxideError",
    "StatsCollector",
    "StartSpiderMiddleware",
    "StopDownload",
    "StrictOriginPolicy",
    "StrictOriginWhenCrossOriginPolicy",
    "StdoutFeedStorage",
    "TextResponse",
    "TakeFirst",
    "UnsafeUrlPolicy",
    "UrlLengthMiddleware",
    "UserAgentMiddleware",
    "XmlResponse",
    "XMLFeedSpider",
    "XmlItemExporter",
    "apply_uri_params",
    "fingerprint",
    "fingerprint_batch",
    "fingerprint_request",
    "fingerprint_requests",
    "get_retry_request",
    "get_settings_priority",
    "resolve_backend",
    "sitemap_urls_from_robots",
    "signals",
]
