"""Safe, switchable request-processing backends for Python crawlers."""

from . import signals
from .api import (
    DupeFilter,
    Scheduler,
    fingerprint,
    fingerprint_batch,
    fingerprint_request,
    fingerprint_requests,
)
from .backend import (
    BACKEND_ENV_VAR,
    BackendChoice,
    BackendUnavailableError,
    resolve_backend,
)
from .cookies import CookiesMiddleware
from .crawl import CrawlSpider, Rule
from .crawler import Crawler, CrawlerRunner
from .depth import DepthMiddleware
from .downloader import Downloader, HttpxDownloader, RustDownloader
from .downloadhandlers import (
    BaseDownloadHandler,
    DataURIDownloadHandler,
    DownloadHandler,
    DownloadHandlers,
    FileDownloadHandler,
    FTPDownloadHandler,
    HTTPDownloadHandler,
    S3DownloadHandler,
)
from .engine import CrawlResult, NativeCrawlEngine
from .exceptions import (
    CloseSpider,
    DownloadError,
    DropItem,
    IgnoreRequest,
    NotConfigured,
    NotSupported,
    SpiderOxideError,
)
from .extensions import ExtensionManager
from .feedexport import (
    BaseItemExporter,
    BlockingFeedStorage,
    CsvItemExporter,
    FeedExporter,
    FeedSlot,
    FileFeedStorage,
    FTPFeedStorage,
    GCSFeedStorage,
    ItemFilter,
    JsonItemExporter,
    JsonLinesItemExporter,
    S3FeedStorage,
    StdoutFeedStorage,
    XmlItemExporter,
)
from .feedpostprocessing import Bz2Plugin, GzipPlugin, LZMAPlugin, PostProcessingManager
from .headers import Headers
from .http import (
    FormRequest,
    HtmlResponse,
    JsonRequest,
    Request,
    Response,
    TextResponse,
    XmlResponse,
)
from .httpcache import (
    DummyPolicy,
    HttpCacheMiddleware,
    NativeHttpCacheStorage,
    RFC2616Policy,
)
from .linkextractors import Link, LinkExtractor, LxmlLinkExtractor
from .pipelines import (
    FileException,
    FileInfo,
    FilesPipeline,
    FSFilesStore,
    ImageException,
    ImagesPipeline,
    MediaPipeline,
)
from .proxy import HttpProxyMiddleware
from .retry import RetryMiddleware, get_retry_request
from .selectors import (
    Compose,
    Identity,
    ItemLoader,
    Join,
    MapCompose,
    SelectJmes,
    Selector,
    SelectorList,
    TakeFirst,
)
from .settings import Settings
from .signals import SignalManager
from .spider import Spider
from .stats import StatsCollector
from .types import (
    Field,
    FingerprintRequest,
    Item,
    ItemAdapter,
    PriorityRequest,
    RequestData,
    ScheduledRequest,
)

__all__ = [
    "BACKEND_ENV_VAR",
    "BackendChoice",
    "BackendUnavailableError",
    "BaseDownloadHandler",
    "BaseItemExporter",
    "BlockingFeedStorage",
    "Bz2Plugin",
    "CloseSpider",
    "Compose",
    "CookiesMiddleware",
    "Crawler",
    "CrawlerRunner",
    "CrawlSpider",
    "CrawlResult",
    "CsvItemExporter",
    "DownloadError",
    "DownloadHandler",
    "DownloadHandlers",
    "Downloader",
    "DataURIDownloadHandler",
    "DummyPolicy",
    "DepthMiddleware",
    "DropItem",
    "DupeFilter",
    "ExtensionManager",
    "Field",
    "FeedExporter",
    "FeedSlot",
    "FileException",
    "FingerprintRequest",
    "FileFeedStorage",
    "FileDownloadHandler",
    "FileInfo",
    "FilesPipeline",
    "FSFilesStore",
    "FormRequest",
    "FTPFeedStorage",
    "FTPDownloadHandler",
    "GCSFeedStorage",
    "GzipPlugin",
    "Headers",
    "HtmlResponse",
    "IgnoreRequest",
    "HttpxDownloader",
    "HTTPDownloadHandler",
    "HttpProxyMiddleware",
    "HttpCacheMiddleware",
    "ImageException",
    "ImagesPipeline",
    "Item",
    "ItemAdapter",
    "ItemFilter",
    "ItemLoader",
    "Identity",
    "JsonItemExporter",
    "JsonLinesItemExporter",
    "JsonRequest",
    "Join",
    "Link",
    "LinkExtractor",
    "LxmlLinkExtractor",
    "LZMAPlugin",
    "MapCompose",
    "MediaPipeline",
    "NotConfigured",
    "NotSupported",
    "NativeCrawlEngine",
    "NativeHttpCacheStorage",
    "PriorityRequest",
    "PostProcessingManager",
    "Request",
    "RequestData",
    "RFC2616Policy",
    "Response",
    "RetryMiddleware",
    "Rule",
    "S3FeedStorage",
    "S3DownloadHandler",
    "RustDownloader",
    "ScheduledRequest",
    "SelectJmes",
    "Scheduler",
    "Selector",
    "SelectorList",
    "Settings",
    "SignalManager",
    "Spider",
    "SpiderOxideError",
    "StatsCollector",
    "StdoutFeedStorage",
    "TextResponse",
    "TakeFirst",
    "XmlResponse",
    "XmlItemExporter",
    "fingerprint",
    "fingerprint_batch",
    "fingerprint_request",
    "fingerprint_requests",
    "get_retry_request",
    "resolve_backend",
    "signals",
]
